version: '3.8'

services:
  user:
    image: dogsub/befly-user:dev
    container_name: befly-user
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: ${{ DB_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ DB_PASSWORD }}
    ports:
      - "8081:8081"
    networks:
      - befly-net

  community:
    image: dogsub/befly-post:dev
    container_name: befly-post
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: ${{ DB_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ DB_PASSWORD }}
    ports:
      - "8083:8083"
    networks:
      - befly-net

networks:
  befly-net:
    external: true
    name: befly-network
