DockerfileFROM openjdk:17-jdk-slim
WORKDIR /app

ARG JAR_FILE=build/libs/community-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8083

EXPOSE 8083

ENTRYPOINT ["java","-jar","app.jar"]
