FROM openjdk:17-jdk-slim
WORKDIR /app

ARG JAR_FILE=build/libs/user-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8081

EXPOSE 8081

ENTRYPOINT ["java","-jar","app.jar"]
